// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: events/event.proto

package events

import (
	_ "github.com/openchatio/proto/pkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body    *EventBody    `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Headers *EventHeaders `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetBody() *EventBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetHeaders() *EventHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

type EventBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*EventBody_NewMessage
	Body isEventBody_Body `protobuf_oneof:"body"`
}

func (x *EventBody) Reset() {
	*x = EventBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBody) ProtoMessage() {}

func (x *EventBody) ProtoReflect() protoreflect.Message {
	mi := &file_events_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBody.ProtoReflect.Descriptor instead.
func (*EventBody) Descriptor() ([]byte, []int) {
	return file_events_event_proto_rawDescGZIP(), []int{1}
}

func (m *EventBody) GetBody() isEventBody_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *EventBody) GetNewMessage() *NewMessageEvent {
	if x, ok := x.GetBody().(*EventBody_NewMessage); ok {
		return x.NewMessage
	}
	return nil
}

type isEventBody_Body interface {
	isEventBody_Body()
}

type EventBody_NewMessage struct {
	NewMessage *NewMessageEvent `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

func (*EventBody_NewMessage) isEventBody_Body() {}

var File_events_event_proto protoreflect.FileDescriptor

var file_events_event_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x13, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6e, 0x65, 0x77,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x5c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x47, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x6f, 0x72, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_event_proto_rawDescOnce sync.Once
	file_events_event_proto_rawDescData = file_events_event_proto_rawDesc
)

func file_events_event_proto_rawDescGZIP() []byte {
	file_events_event_proto_rawDescOnce.Do(func() {
		file_events_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_event_proto_rawDescData)
	})
	return file_events_event_proto_rawDescData
}

var file_events_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_event_proto_goTypes = []interface{}{
	(*Event)(nil),           // 0: org.openchat.events.Event
	(*EventBody)(nil),       // 1: org.openchat.events.EventBody
	(*EventHeaders)(nil),    // 2: org.openchat.events.EventHeaders
	(*NewMessageEvent)(nil), // 3: org.openchat.events.NewMessageEvent
}
var file_events_event_proto_depIdxs = []int32{
	1, // 0: org.openchat.events.Event.body:type_name -> org.openchat.events.EventBody
	2, // 1: org.openchat.events.Event.headers:type_name -> org.openchat.events.EventHeaders
	3, // 2: org.openchat.events.EventBody.new_message:type_name -> org.openchat.events.NewMessageEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_events_event_proto_init() }
func file_events_event_proto_init() {
	if File_events_event_proto != nil {
		return
	}
	file_events_headers_proto_init()
	file_events_new_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_events_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_events_event_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*EventBody_NewMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_event_proto_goTypes,
		DependencyIndexes: file_events_event_proto_depIdxs,
		MessageInfos:      file_events_event_proto_msgTypes,
	}.Build()
	File_events_event_proto = out.File
	file_events_event_proto_rawDesc = nil
	file_events_event_proto_goTypes = nil
	file_events_event_proto_depIdxs = nil
}
