// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: types/error_codes.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCodes int32

const (
	ErrorCodes_Ok               ErrorCodes = 0
	ErrorCodes_InvalidSignature ErrorCodes = 1
)

// Enum value maps for ErrorCodes.
var (
	ErrorCodes_name = map[int32]string{
		0: "Ok",
		1: "InvalidSignature",
	}
	ErrorCodes_value = map[string]int32{
		"Ok":               0,
		"InvalidSignature": 1,
	}
)

func (x ErrorCodes) Enum() *ErrorCodes {
	p := new(ErrorCodes)
	*p = x
	return p
}

func (x ErrorCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_types_error_codes_proto_enumTypes[0].Descriptor()
}

func (ErrorCodes) Type() protoreflect.EnumType {
	return &file_types_error_codes_proto_enumTypes[0]
}

func (x ErrorCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCodes.Descriptor instead.
func (ErrorCodes) EnumDescriptor() ([]byte, []int) {
	return file_types_error_codes_proto_rawDescGZIP(), []int{0}
}

var File_types_error_codes_proto protoreflect.FileDescriptor

var file_types_error_codes_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6f, 0x72, 0x67, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x2a, 0x0a,
	0x0a, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x6b, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x10, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x74,
	0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_types_error_codes_proto_rawDescOnce sync.Once
	file_types_error_codes_proto_rawDescData = file_types_error_codes_proto_rawDesc
)

func file_types_error_codes_proto_rawDescGZIP() []byte {
	file_types_error_codes_proto_rawDescOnce.Do(func() {
		file_types_error_codes_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_error_codes_proto_rawDescData)
	})
	return file_types_error_codes_proto_rawDescData
}

var file_types_error_codes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_error_codes_proto_goTypes = []interface{}{
	(ErrorCodes)(0), // 0: org.openchat.types.ErrorCodes
}
var file_types_error_codes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_error_codes_proto_init() }
func file_types_error_codes_proto_init() {
	if File_types_error_codes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_error_codes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_error_codes_proto_goTypes,
		DependencyIndexes: file_types_error_codes_proto_depIdxs,
		EnumInfos:         file_types_error_codes_proto_enumTypes,
	}.Build()
	File_types_error_codes_proto = out.File
	file_types_error_codes_proto_rawDesc = nil
	file_types_error_codes_proto_goTypes = nil
	file_types_error_codes_proto_depIdxs = nil
}
